### ISSUE TITLE
Unable to build dev package

### ISSUE THREAD

**Issue by earada** [lief-project/packages#2]
Since a few days ago, I'm unable to build dev package.  It tries to access `https://github.com/lief-project/packages/raw/lief-master-latest/lief-0.7.0-py2.7-linux.egg` which returns 404.

```
# pip install https://github.com/lief-project/packages/raw/lief-master-latest/pylief-0.7.0.dev.zip
Collecting https://github.com/lief-project/packages/raw/lief-master-latest/pylief-0.7.0.dev.zip
  Downloading https://github.com/lief-project/packages/raw/lief-master-latest/pylief-0.7.0.dev.zip
  Requirement already satisfied (use --upgrade to upgrade): lief==0.7.0 from https://github.com/lief-project/packages/raw/lief-master-latest/pylief-0.7.0.dev.zip in /usr/local/lib/python2.7/dist-packages
Building wheels for collected packages: lief
  Running setup.py bdist_wheel for lief ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-7Mn8BH-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpWBYJQYpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/lief
  copying lief/__init__.py -> build/lib.linux-x86_64-2.7/lief
  running build_ext
  Url: https://github.com/lief-project/packages/raw/lief-master-latest/lief-0.7.0-py2.7-linux.egg
  HTTP Error 404: Not Found
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-7Mn8BH-build/setup.py", line 206, in <module>
      'sdist':     lief_sdist
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/dist-packages/setuptools/command/build_ext.py", line 75, in run
      _build_ext.run(self)
    File "/usr/lib/python2.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/usr/lib/python2.7/distutils/command/build_ext.py", line 449, in build_extensions
      self.build_extension(ext)
    File "/tmp/pip-7Mn8BH-build/setup.py", line 136, in build_extension
      self._install_from_source_package()
    File "/tmp/pip-7Mn8BH-build/setup.py", line 186, in _install_from_source_package
      raise Exception("Unable to find {}".format(url))
  Exception: Unable to find /root/lief-0.7.0-py2.7-linux.egg

  ----------------------------------------
  Failed building wheel for lief
  Running setup.py clean for lief
Failed to build lief
```

**Comment by romainthomas** [comment]
Seems Travis didn't upload the package for Python 2.7. I'm looking for the error

**Comment by romainthomas** [comment]
Need to wait that Ubuntu fix https://travis-ci.org/lief-project/LIEF/jobs/284149864#L660

**Comment by earada** [comment]
Thanks for the quick response @romainthomas, I hope the mongo guys will update their GPG Key soon.

**Comment by romainthomas** [comment]
Should be fixed. Could you test ?

**Comment by earada** [comment]
It works now, thanks!
