### ISSUE TITLE
No packages availables for python 3.5 and 3.6

### ISSUE THREAD

**Issue by Rafiot** [lief-project/packages#3]
There are no linux egg packages for python 3.* any more there: https://github.com/lief-project/packages/tree/lief-master-latest

So installing the package will fail:

```
$ (git::master) pip install https://github.com/lief-project/packages/raw/lief-master-latest/pylief-0.7.0.dev.zip
Collecting https://github.com/lief-project/packages/raw/lief-master-latest/pylief-0.7.0.dev.zip
  Using cached https://github.com/lief-project/packages/raw/lief-master-latest/pylief-0.7.0.dev.zip
  Requirement already satisfied (use --upgrade to upgrade): lief==0.7.0 from https://github.com/lief-project/packages/raw/lief-master-latest/pylief-0.7.0.dev.zip in /home/raphael/.local/share/virtualenvs/pymisp3/lib/python3.5/site-packages
Building wheels for collected packages: lief
  Running setup.py bdist_wheel for lief ... error
  Complete output from command /home/raphael/.local/share/virtualenvs/pymisp3/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/tmp/pip-fmxya1m9-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp6mzb3ze0pip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/lief
  copying lief/__init__.py -> build/lib.linux-x86_64-3.5/lief
  running build_ext
  Url: https://github.com/lief-project/packages/raw/lief-master-latest/lief-0.7.0-py3.5-linux.egg
  HTTP Error 404: Not Found
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-fmxya1m9-build/setup.py", line 206, in <module>
      'sdist':     lief_sdist
    File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/raphael/.local/share/virtualenvs/pymisp3/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/raphael/.local/share/virtualenvs/pymisp3/lib/python3.5/site-packages/setuptools/command/build_ext.py", line 75, in run
      _build_ext.run(self)
    File "/usr/lib/python3.5/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/usr/lib/python3.5/distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/usr/lib/python3.5/distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-fmxya1m9-build/setup.py", line 136, in build_extension
      self._install_from_source_package()
    File "/tmp/pip-fmxya1m9-build/setup.py", line 186, in _install_from_source_package
      raise Exception("Unable to find {}".format(url))
  Exception: Unable to find /home/raphael/lief-0.7.0-py3.5-linux.egg

```

**Comment by romainthomas** [comment]
Seems related to #2. I'll look at it

**Comment by romainthomas** [comment]
Should be fixed

**Comment by Rafiot** [comment]
Yep, it is, thanks :)
